Fix workflow error about missing pom.xml files
Error: No file in /home/runner/work/extension-manager/extension-manager matched to [**/pom.xml], make sure you have checked out the target repository