Exclude aXMLRPC because it breaks tests
java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
 at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
 at com.exasol.mavenprojectversiongetter.MavenProjectVersionGetter.getPropertyOfXmlFile(MavenProjectVersionGetter.java:98)